//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT ME.
        /// </summary>
        internal static string ABOUTME {
            get {
                return ResourceManager.GetString("ABOUTME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactUs.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePageWelcomeMessage.
        /// </summary>
        internal static string HomePageWelcomeMessage {
            get {
                return ResourceManager.GetString("HomePageWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StajdaÖğrendiklerimAltıncıParagraf.
        /// </summary>
        internal static string StajdaOgrendiklerimAlt�nc�Paragraf {
            get {
                return ResourceManager.GetString("StajdaOgrendiklerimAlt�nc�Paragraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StajdaÖğrendiklerimBesinciParagraf.
        /// </summary>
        internal static string StajdaOgrendiklerimBesinciParagraf
		{
            get {
                return ResourceManager.GetString("StajdaOgrendiklerimBesinciParagraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StajdaÖğrendiklerimDördüncüParagraf.
        /// </summary>
        internal static string StajdaOgrendiklerimDorduncuParagraf {
            get {
                return ResourceManager.GetString("StajdaOgrendiklerimDorduncuParagraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StajdaÖğrendiklerimÜcüncüParagraf.
        /// </summary>
        internal static string StajdaOgrendiklerimUcuncuParagraf
		{
            get {
                return ResourceManager.GetString("StajdaOgrendiklerimUcuncuParagraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StajdaÖğrendiklerimİkinciParagraf.
        /// </summary>
        internal static string StajdaOgrendiklerimIk�nc�Paragraf
		{
            get {
                return ResourceManager.GetString("StajdaOgrendiklerimIk�nc�Paragraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StajdaÖğrendiklerimİlkParagraf.
        /// </summary>
        internal static string StajdaOgrendiklerimIlkParagraf
		{
            get {
                return ResourceManager.GetString("StajdaOgrendiklerimIlkParagraf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatItIs.
        /// </summary>
        internal static string WhatItIs {
            get {
                return ResourceManager.GetString("WhatItIs", resourceCulture);
            }
        }
    }
}
